### ISSUE TITLE
Scrolling is difficult on iPad + Safari

### ISSUE THREAD

**Issue by arnoldbird** [nolanlawson/pinafore#123]
On an iPad, in Safari, every fourth or fifth swipe up, the scrolling will get catch and get stuck.  From there, you either have reload the page, or swipe up three or four times until it gets unstuck, and then scrolling will working again, temporarily.
 
No problem in Firefox on IPad.

**Comment by nolanlawson** [comment]
What version of iOS are you running? Does it only happen when swiping up, or when swiping down too?

**Comment by technopagan** [comment]
I just noticed this for the first time when scrolling through the local timeline view: after scrolling down a lot, I went to the details view of one toot and then back to the local timeline view. At this point, the scrolling became stuck: only the toots that were visible in the viewport at that moment remained & I couldn’t scroll up or down because the browser didn’t seem to realize that there was more content outside the viewport. What “fixed” it for me was opening an image that was embedded in one of the remaining toots & then closing its overlay view again using the “X” in the top right corner. After that, the timeline had all its contents again. 

Device: iPad Pro 10.5, iOS 11.3, stock Safari browser

**Comment by nolanlawson** [comment]
So does this only occur on iPad? I have tested on an iPod Touch and haven't observed any issues with scrolling. If anyone can catch this in the act and show a profile trace from Safari Web Inspector, that may help identify the issue. :)

**Comment by nolanlawson** [comment]
should be fixed by #655
