### ISSUE TITLE
Pinafore doesn't load on Firefox 67.0.3

### ISSUE THREAD

**Issue by sajeshcherian** [nolanlawson/pinafore#1294]
For some reason, Pinafore won't load on latest version of Firefox. It runs fine on Chromium. The information bar on Firefox says "Blockable content detected on this site" which is very weird as Pinafore doesn't have any tracking tools. I tried setting the Content Blocking to all three available options - "Standard", "Strict", and "Custom" and allowed Pinafore to Set Cookies in Firefox explicitly but that doesn't help. On the Add Instance page, this is what I am stuck with "Error: NetworkError when attempting to fetch resource.. Is this a valid Mastodon instance? Is a browser extension blocking the request? Are you in private browsing mode?". And I am not in Private Browsing mode either. Any help is appreciated.

![Screenshot from 2019-06-23 11-59-58](https://user-images.githubusercontent.com/19327775/59979511-76b60800-95ae-11e9-8937-fa9190da0bf0.png)

**Comment by nolanlawson** [comment]
The best way to check is to look in the dev tools console to see what the error is.

Oddly I use Firefox myself and have never run into this. It could be the same class of errors that Privacy Badger causes: #411

**Comment by nolanlawson** [comment]
Also I believe what you may need to do is to authorize _your Mastodon instance_ to run "third-party cookies" on Pinafore. What Firefox is blocking is the Mastodon instance, because it looks like a third-party tracker from Firefox's perspective.

Hope that helps, closing this issue since I've not repro'd locally and it looks like similar issues we've had with Privacy Badger.
