### ISSUE TITLE
Back button and link sometimes take me to the top of home timeline

### ISSUE THREAD

**Issue by spriteclad** [nolanlawson/pinafore#1498]
As it says in the title. I have this problem with stock Safari in iOS 13.1 beta. It just sometimes takes me back to the top of the timeline no matter what back button I hit.

**Comment by nolanlawson** [comment]
Hmmm, I think this bug was reported before, and I could have sworn it was fixed. Can you repro in any other browser or environment? (Testing other browsers on iOS is probably not useful since they all use the Safari WebKit engine under the hood.) Does it matter whether you click the link or use the browser back button? Does it only happen when you tap the "Back" link on threads?

**Comment by spriteclad** [comment]
Here's evidence of Pinafore doing that on my device. It does it no matter what Back button is pushed, whether it be a link or the browser button.

http://spriteclad.com/i/IMG_0299.MP4

Also, it never does this on desktop Firefox, only iOS.

**Comment by nolanlawson** [comment]
Can't repro on iOS 14.4.1. Please reopen if this is still reproducible.
