### ISSUE TITLE
Can't connect to an instance.

### ISSUE THREAD

**Issue by rkingett** [nolanlawson/pinafore#1791]
On the Booktoot.club instance, I always get the below error when all other instances are fine. Is this a client issue, or an instance issue?

Error: Window.fetch: https://weirdwriter@booktoot.club/api/v1/instance is an url with embedded credentials.. Is this a valid Mastodon instance? Is a browser extension blocking the request? Are you in private browsing mode?

**Comment by nolanlawson** [comment]
Hi, please send the following document to the admin of your instance: https://github.com/nolanlawson/pinafore/blob/master/docs/Admin-Guide.md

Somehow, this instance is configured to not support cross-origin requests, which is why Pinafore doesn't work. I checked myself and can confirm that this command:

```
curl -sLv booktoot.club/api/v1/instance -o /dev/null
```

Does not show an `Access-Control-Allow-Origin` header. I hope that helps! :)

**Comment by nolanlawson** [comment]
I stand corrected. It looks like the issue is that you included your username `weirdwriter` in the instance name. Just enter `booktoot.club` and it should work. :slightly_smiling_face:
