### ISSUE TITLE
Not receiving streaming updates on my instance

### ISSUE THREAD

**Issue by Shadow8t4** [nolanlawson/pinafore#1829]
I'm fairly certain this has something to do with the way my instance is configured more than it has to do with Pinafore, but it's a strange quirk nonetheless, and I want to see if I can get it fixed.

I am not receiving streaming post updates on Pinafore, I can get them just fine on any other instance, and I can get them on my instance on other front-ends (Masto FE and Halcyon). My only conclusion is I've either configured something in a way Pinafore doesn't like, or there's a problem with Pinafore handling my instance the way it's configured.

![Annotation 2020-07-06 153156](https://user-images.githubusercontent.com/12878429/86641567-d8ba9300-bfa0-11ea-978f-99115bb69b40.png)

Here's a screenshot of what I see in the console, I can tell that it probably has to do with that Network Error, but I don't know enough about what it's doing to understand why I'm getting it.

**Comment by nolanlawson** [comment]
Interesting, it looks like it's trying to load a font but failing due to Content Security Policy. I don't have any fonts in Pinafore, so I'm not sure how this is happening. It might be due to an extension, because it looks like `moz-extension` is also active there.

So when you test on `pinafore.social` it doesn't reproduce; it only reproduces in your self-hosted Pinafore? Or when you say "my instance" are you referring to your Mastodon instance?

**Comment by nolanlawson** [comment]
Have you tried in another browser without any extensions and without changing any of the default settings? It could also be a browser-specific issue.

**Comment by Shadow8t4** [comment]
"Source map error" is what's happening when I log into `masto.werefox.dev` on `pina.werefox.dev`. I can go log in to `masto.werefox.dev` on `pinafore.social` to see if that gets rid of it.

The other errors don't really seem to be affecting anything, and I don't think thow show up in Chrome. Just the source map error. That shows up in all browsers I've tried (Firefox, Firefox iOS, Chrome, Edge (chromium-based)).

**Comment by Shadow8t4** [comment]
On both `pinafore.social` and `pina.werefox.dev`, attempting to view the Federated Timeline when logged into `masto.werefox.dev` give this error in the console on Firefox. 

![Annotation 2020-07-07 102046](https://user-images.githubusercontent.com/12878429/86803404-92664200-c03b-11ea-82f6-d509bd987f78.png)

The error doesn't appear on `pinafore.social` or `pina.werefox.dev` when logged into other instances.

**Comment by nolanlawson** [comment]
Based on [this Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=743911), this still appears to be a CSP or cross-origin security issue. Since it's only reproducible on other instances, I'm thinking it must be due to the `Access-Control-Allow-Origin` headers on `masto.werefox.dev`.

I tried doing a basic curl test:

```sh
curl -H "Origin: https://pinafore.social"  -H "Access-Control-Request-Method: GET"  -H "Access-Control-Request-Headers: X-Requested-With"  -X OPTIONS --verbose https://masto.werefox.dev/api/v1/instance
```

However, this produced the same access control headers as my own instance `toot.cafe` which works fine. So now I'm wondering if it's something specific to the WebSocket protocol (`wss:`), but curl doesn't support that so I'm not sure how to test.

In Firefox, you may be able to figure this out by looking at the Network tab and checking for why the WebSocket connection failed.

**Comment by nolanlawson** [comment]
Please reopen if my diagnosis is incorrect or I missed something!
