### ISSUE TITLE
iOS < 12.2 workaround breaks PWA rendering in iOS 13

### ISSUE THREAD

**Issue by amyspark** [nolanlawson/pinafore#1832]
#1550 relied on a workaround to disable the PWA manifest on iOS versions earlier than 12.2.
In Safari 13, IntersectionObserver is an experimental feature, **there Pinafore will not work as a PWA** unless it is enabled first.
A very quick smoke test to verify this bug is to add Pinafore to the home screen, and check the app's URL. If the manifest is not found, it will lack the "/?pwa=1" query string.

**Comment by nolanlawson** [comment]
Thanks for reporting the issue. Looking at [caniuse](https://caniuse.com/#feat=intersectionobserver), it appears that IntersectionObserver is still a fully-supported feature in Safari 13? Which version of iOS are you seeing this issue on?

**Comment by nolanlawson** [comment]
OK, on iOS 13.6.1, I see that IntersectionObserver is listed in the experimental features, but on my iPod Touch, it is enabled by default. It seems unlikely to me that a user would go into these settings and disable it, and in those cases, I think it's reasonable to say that any breakages are on them rather than me. :slightly_smiling_face: 

Closing for now, let me know if I've misdiagnosed this!
