### ISSUE TITLE
Unable to run in dev mode (Windows)

### ISSUE THREAD

**Issue by kapilbhavsar** [nolanlawson/pinafore#1919]
I'm trying to run in dev mode getting this error:

C:\Users\kapil\source\repos\pinafore>yarn run dev
yarn run v1.22.10
$ run-s build-template-html build-assets serve-dev
$ node -r esm ./bin/build-template-html.js
Built template.html in 1284.81ms
$ node -r esm ./bin/build-assets.js
$ run-p --race build-template-html-watch sapper-dev
$ node -r esm ./bin/build-template-html.js --watch
$ cross-env NODE_ENV=development PORT=4002 node -r esm ./node_modules/.bin/sapper dev
C:\Users\kapil\source\repos\pinafore\node_modules\.bin\sapper:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (vm.js:355:18)
    at Generator.next (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "sapper-dev" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "serve-dev" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by nolanlawson** [comment]
Pinafore hasn't been configured to work properly on Windows yet. You may want to try Windows Subsystem for Linux.

**Comment by nolanlawson** [comment]
Also it looks like this bug is in Sapper, which we are using an older fork of.

**Comment by dstaley** [comment]
@nolanlawson I'd love to see about getting this building on Windows. I assume the first step would be upgrading Sapper. Do you know if the reason Pinafore is using a fork of Sapper is still valid?

**Comment by nolanlawson** [comment]
We're stuck on a Sapper fork because I made quite a few modifications, plus we're stuck on Svelte v2 unless we manually upgrade the whole site to Svelte v3 (not likely to happen). Also Sapper is an abandoned project: https://kit.svelte.dev/migrating

Probably the Sapper fork would just need some tweaks: https://github.com/nolanlawson/sapper/

Else you can build the project using Windows Subsystem for Linux and run it using another Windows terminal. I'd also like to finish getting the nginx config generator done at some point, at which point I could potentially just publish the build artifacts and nobody would have to worry about being able to build it across platforms. :)
