### ISSUE TITLE
no focus ring after interaction with mouse

### ISSUE THREAD

**Issue by ndalliard** [nolanlawson/pinafore#2038]
i am using firefox

i don't get the focus ring back when using the mouse (either by clicking on a toot in general, by clicking on a link, boosting, starring or by clicking on the menu on the top), there is the exception, that when i click on the right or left side of the timeline, the focus ring comes back. i have to reload the whole app/page to get the focus ring back

**Comment by nolanlawson** [comment]
This is because of how I'm using the focus-visible polyfill for Firefox. It uses heuristics that don't always match user expectations.

If you want to always show the focus ring, there is an option "Always show focus ring" in the General settings under Accessibility. Eventually I also plan to move Firefox back to the native focus-visible implementation, which would typically allow you to set this globally at your OS level.

Hope that helps!

**Comment by nolanlawson** [comment]
This PR moves Firefox back to the native focus-visible implementation ^

**Comment by ndalliard** [comment]
thanks - my bad, didn't try the «always show focus ring» settings, that works for me! the switch back to native focus-visible on firefox doesn't change anything in my case (at least that i am aware of), but as said, the setting works for me
