### ISSUE TITLE
Scrolling is all sorts of messed up on some browsers

### ISSUE THREAD

**Issue by Granitosaurus** [nolanlawson/pinafore#219]
There seems to be some weird scrolling issues going on some browsers.

For example I'm running latest Qutebrowser and scrolling tends to stop working at random.   
To add to that scrolling doesn't work when loading the page for the first time - you need to select toot are for it to start working.

**Comment by nolanlawson** [comment]
Qutebrowser is WebKit-based, right? Or do you have the update where it's Chromium-based? Also I assume this is Linux desktop, and you're scrolling with the mousewheel or keyboard or some other non-touch method?

There is a similar issue for Safari, which is also Webkit: #123. I wonder if it's related.

Scrolling ought to work when you first load the page since #99 was fixed; not sure why it's not in your case.

**Comment by Granitosaurus** [comment]
Qutebrowser is webengine based.  

I cannot replicate or figure out what the issue it seems to stop completely randomly - sometimes it's fine for several pages. 

To add to that other scroll functions don't work either like scroll by percantage. Seems like qutebrowser is confused by header + content box structure pinafore is using :|

**Comment by nolanlawson** [comment]
Since Qutebrowser is WebKit-based, this may be related to #123.

**Comment by Granitosaurus** [comment]
Qutebrowser is based on webengine (chromium). There is support for webkit but webkit being deprecated makes it pretty much dead and useless.

**Comment by nolanlawson** [comment]
I'm going to assume this is fixed by https://github.com/nolanlawson/pinafore/pull/656
