### ISSUE TITLE
move mute and follow buttons from under "more options", possibly get rid of it entirely.

### ISSUE THREAD

**Issue by Granitosaurus** [nolanlawson/pinafore#223]
Muting is great way to clear up your feed and should be encouraged. 
There's a lot of space below posts, enough to fit all of the buttons actually.

I rarely use block but mute and follow and really common, I'd be willing to bet that those buttons are used way more often than boost button for example.

Nevertheless I think there's plenty of space for all buttons to be expanded.

**Comment by codl** [comment]
i'm against this.

aesthetics aside (i think it would look goofy to have so many buttons there), those buttons are all over the TL and are easy to misclick.

when twitter added a follow action button to every tweet on the mobile apps, i was constantly worried that I'd follow someone I didn't mean to when i was trying to scroll. this is even worse with blocks because you can't just undo a block, if they followed you and you blocked them, unblocking them isn't going to make them follow you again

adding a confirmation step to those buttons would defeat the point of them being quick to access

also I certainly boost way more often than I mute or follow. judging from my timeline, I'm not the only one :/

**Comment by rowanlupton** [comment]
I rarely follow or block, I boost frequently. I'm surprised your experience is so different! I'm also terrified of accidentally following somebody — accidentally faving a toot is bad enough. :)

**Comment by Granitosaurus** [comment]
I think missclicks and aesthetics are bad arguments and should be solved more intelligently anyway.

Aesthetics:
There just seems so much pointless whitespace with one column and unnecessary "more options" buttons. Information is good and should be encouraged and 2 more icons will hardly change anything.

Missclicks:
Missclicks should be solved in other ways - smaller buttons, bigger gaps, bigger button contracts etc. Solving that by hiding them away with somewhere in the menu is lazy design that really is there just to hide the issue rather than to solve it.


To add to that a fullscreen dim/fake pop up is really distracting as well - it takes long to appear, blocks all of the content and content behind is still still clickable, interactive (breaking keyboard based browsers etc.)

![image](https://user-images.githubusercontent.com/5476164/39320704-7fe1f254-4974-11e8-87bd-c9519ee4ce45.png)

**Comment by rowanlupton** [comment]
There’s a lot less whitespace on mobile!

**Comment by codl** [comment]
oh something else to note is that that menu is probably going to have more options yet, when reporting, muting conversations, embedding statuses; are implemented. so it's probably not going to go away entirely

**Comment by nolanlawson** [comment]
Yeah the inert issue seems like a Qutebrowser issue. I'm using [a11y-dialog](https://github.com/edenspiekermann/a11y-dialog) which is following standard a11y advice AFAIK.

Also I tend to agree with @codl that it would add too much clutter to add the mute/follow buttons there. On desktop the design probably does have a bit too much wasted space, but for the time being I'm optimizing for small screens since it's the lowest-common denominator. I'm inclined to close this issue due to design disagreement, but I appreciate the spirited discussion. :)

**Comment by Granitosaurus** [comment]
Welp I'm disappointed to hear no fair rebutals or alternative suggestions.
There's probably more ways to solve this issue than to just expand everything, put a setting in it. 
expand all option once post is clicked (e.g. what reddit mobile app does) etc.

But seems like the maintainers are set on their monolith. :man_shrugging:
