### ISSUE TITLE
Add a shortcut for the Bookmark action

### ISSUE THREAD

**Issue by pitermach** [nolanlawson/pinafore#2237]
The official Mastodon interface includes a Bookmark button next to every post, making it relatively easy to access. Likewise some mobile apps like Metatext offer "Bookmark" action, which again makes it very fast to do. In contrast, to bookmark a post in Pinafore you need to find it in the more menu which takes a lot of keystrokes. This is in contrast to the favorite command which is just 1 shortcut.

To this end I propose that the Bookmark command also get a keyboard shortcut. Since B, O, M, R and K are all taken I suggest the letter A. Like the Boost and Favorite actions it should also get a spoken confirmation through Aria if it's pressed.

**Comment by jcsteh** [comment]
I would love this and was thinking about how to implement it. However, it occurred to me that this would be tricky visually.

The Bookmark button isn't shown unless you open the More options menu. Even though we could announce a message to screen readers, I guess it'd be trickier to show this visually, since there's no button/icon to act as an indicator. That said, I did notice that bookmarking a toot does pop up a little alert, so if that alert is also visible, that might be enough?

**Comment by nolanlawson** [comment]
I was thinking the simplest solution would be:

1. Add a keyboard shortcut ("A" is fine)
2. When you tap the key, it uses an aria-live region to say "Bookmarked" or "Unbookmarked" (similar to the shorcuts for fav/boost)

Adding a new button is not something I'm crazy about, given that I worry the UI is already a bit cluttered, and bookmarking is not a feature that everybody uses...

**Comment by jcsteh** [comment]
That'd be perfect. I was just trying to figure out how you'd make that work visually. Would the live region also flash up visually?
