### ISSUE TITLE
Notification page has low contrast for toots

### ISSUE THREAD

**Issue by NickColley** [nolanlawson/pinafore#2249]
![](https://user-images.githubusercontent.com/2445413/203989852-95f0883e-f67f-4d49-bde7-b6cf78ab745a.png)

 think perhaps a way forwards is to remove the status toolbar controls from these toots and increase the contrast so it at least meets WCAG requirements.

![](https://user-images.githubusercontent.com/2445413/203990463-89d6a618-d660-4807-85e0-1a729629afe5.png)

**Comment by nolanlawson** [comment]
I guess these ones don't technically need the toolbar, yeah. You can just click through to see the controls. Maybe that's fine anyway, since the UI is probably already cluttered with them due to no coalescing: #2184 

Increasing the contrast on these is great IMO as long as there is still some affordance that this is a "status within a notification" and in some sense "inert." Also the "so-and-so favorited" text should stand out more than the toot text itself, since that's what's really important. It's a tough one. :confused:
