### ISSUE TITLE
Poles always show as ending never

### ISSUE THREAD

**Issue by TheQuinbox** [nolanlawson/pinafore#2286]
No matter if you're voting on or creating a pole, the ending date always shows as "Never", even after the pole has ended and is in your notifications.

**Comment by graue** [comment]
Yes, I'm also seeing polls all say they end never. Hometown v1.0.7+3.5.5 server if it matters.

**Comment by TheQuinbox** [comment]
I'm also on Hometown, if it matters.

**Comment by tbroyer** [comment]
This also happens to me with a Mastodon v4.0.2 server.

I'd say this is because Pinafore expects the server to return the `expires_at` as a number:

https://github.com/nolanlawson/pinafore/blob/fb5478cd06bcdedda7dbd1a8309f099fae3b0508/src/routes/_components/status/StatusPoll.html#L308-L310

whereas the API says it's an ISO-formatted string: https://docs.joinmastodon.org/entities/Poll/#expires_at

Maybe just replace that `typeof expiresAt === 'number'` test to `expiresAt != null`?

**Comment by nolanlawson** [comment]
Thanks yeah, looks like Mastodon v4 uses strings now.
