### ISSUE TITLE
Define "types of toots" and adjust display accordingly?

### ISSUE THREAD

**Issue by skiant** [nolanlawson/pinafore#302]
This is more of a discussion I'd like to have than an actual feature request, but I think that there are different kind of messages posted by people on social networks like Mastodon, and it would be neat to see the UI acknowledge that not all of those are equal.

For instance, posts with one to four pictures and no text (except maybe the usual "." that people use to circumvent the empty toot issue) could have a picture-centric display.
Posts that contains a massive text content could be displayed in a way that's more suited for long text readability.

**Comment by nolanlawson** [comment]
I could see this as an option in the Pinafore settings, as described in https://github.com/nolanlawson/pinafore/issues/258. I think it would have to be a user setting rather than something we try to sniff on a per-toot basis, though. E.g. someone surfing mastodon.art probably has different needs than someone surfing wandering.shop, so hopefully they could choose slightly different UIs for each (most likely a small-media UI for wandering.shop).

Closing since #258 seems to cover it. Thanks!

**Comment by skiant** [comment]
I'm not sure I fully agree with the assumption that people would make one account on each server they are interested in and/or follow only people posting one type of toot. With the release of Federation in Pixelfed and the work being put in Peertube and Plume, you could follow people with very different types of posting and I'd love to see a client like Pinafore understand this, but I do understand if it's not a goal of yours.
