### ISSUE TITLE
Pinafore not working with instance once instance upgraded to Masto v2.4

### ISSUE THREAD

**Issue by M-D-M** [nolanlawson/pinafore#354]
Instance is https://mcnamarii.town.  

Error being received upon trying to add instance to Pinafore: 

> Firefox 60.0.1 (Linux): "Error: NetworkError when attempting to fetch resource.. Is this a valid Mastodon instance? Is a browser extension blocking the request?"
> 
> Chrome 66.0.3359.181 (Linux): "Error: Failed to fetch. Is this a valid Mastodon instance? Is a browser extension blocking the request?"
> 
> Safari (iPhone): "Error: type error: Is this a valid Mastodon instance?  Is a browser extension blocking the request?"

Running stock mastodon instance.  Only nginx config change when upgrading to v2.4 was the following:

`add_header Access-Control-Allow-Origin 'https://mcnamarii.town/';`

**Comment by nolanlawson** [comment]
right, so that Access-Control-Allow-Origin is [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) which would cause exactly the bug you describe. You have a few options:

- change to `Access-Control-Allow-Origin *`
- add `Access-Control-Allow-Origin 'https://pinafore.social'`

Closing since it appears this is not a 2.4 issue but rather a CORS issue.
