### ISSUE TITLE
Image description input unreadable when using darker themes

### ISSUE THREAD

**Issue by igalic** [nolanlawson/pinafore#368]
When using a darker theme, such as Ozark or Sorcery, the input for an image caption is practically unreadable, since the text in the input box is black — on dark background:

Before entering anything (as you can hopefully see, the word "Description" is clearly [enough] visible):

![Example post before anything is entered as Description](https://user-images.githubusercontent.com/497249/40923376-f609dd52-6814-11e8-9bbb-7502df46870b.png)

When entering text:

![This text is practically invisible is now entered instead of "Description" and it's practically invisible](https://user-images.githubusercontent.com/497249/40923555-5c325172-6815-11e8-8bc9-32c96b883bd8.png)

**Comment by igalic** [comment]
(see here https://mastodon.social/@hirojin/100147071674873739 )

**Comment by nolanlawson** [comment]
Thanks yes, this looks like a bug in the dark themes!

**Comment by nolanlawson** [comment]
The dark theme base file is defined in [_dark.scss](https://github.com/nolanlawson/pinafore/blob/master/scss/themes/_dark.scss) so hopefully that should be the only place we need to fix this. (Otherwise it's in sorcery.scss, ozark.scss, and cobalt.scss.) The CSS classes for that text are defined here: https://github.com/nolanlawson/pinafore/blob/2b473d261f028ffc2bc39976d7aceb6ad0c237a3/routes/_components/compose/ComposeMediaItem.html#L45-L49

**Comment by nolanlawson** [comment]
Hmm looks like we may need a new CSS variable for this. There is `--alt-input-bg` but apparently no `--alt-input-color` (or similar). I assume it's just inheriting the font color from somewhere else.
