### ISSUE TITLE
revoked permission leads to "internet request fails. Showing offline content."

### ISSUE THREAD

**Issue by pkra** [nolanlawson/pinafore#398]
It took me a while to connect the dots but I'm reasonably certain that revoking permissions lead to the offline error messsage; I'm not sure if it's a bug or a missing feature.

This happened to me on pinafore.social, using current Firefox on Android.

**Comment by pkra** [comment]
Not sure if it's worth a separate issue but when I look up instances, the relveant (only) instance was still listed as "logged in"; after logging out and back everything is working again (unsurprisingly -- thanks for such a great tool!).

**Comment by nolanlawson** [comment]
Yup, I think this is the standard solution for when you revoke a token – you log out and log back in again. Pinafore _could_ try to detect that a request was invalid because the token expired as an enhancement, though, and change the error message, but it's such a small use case that I'm not sure if it's worth the effort.

**Comment by pkra** [comment]
Thanks for the response; makes sense.
