### ISSUE TITLE
Warn users about Privacy Badger and the likes

### ISSUE THREAD

**Issue by Vinnl** [nolanlawson/pinafore#411]
I just found out that Privacy Badger was the reason I stopped seeing new posts and only saw connection errors in Pinafore (#23). While I understand that this will be hard to circumvent (since trackers would then be able to do so as well), it might be an idea to perhaps show a hint to the users to disable add-ons like Privacy Badger on e.g. three consecutive connection errors?

**Comment by nolanlawson** [comment]
There is already a warning ("do you have a browser extension that is blocking Pinafore," etc.). I'm not sure if I can detect Privacy Badger itself and provide a Privacy Badger-specific warning (AIUI Privacy Badger should prevent that kind of thing because it violates… privacy 😉).

Closing as there is already a warning and I'm concerned it would be too specific of an error message and may confuse folks who _aren't_ using privacy badger, but I appreciate the issue!

**Comment by Vinnl** [comment]
Hmm, sorry about that - I must've missed that warning, or it's a recent addition; it only said something like "No network connection" for me. If there's a warning already, that's exactly what I meant with this issue :)
