### ISSUE TITLE
Use custom strings

### ISSUE THREAD

**Issue by jemus42** [nolanlawson/pinafore#429]
On cybre.space, likes are florps and boosts are relays and such and such, which is reflected in the UI via, I believe, a custom language setting.  
Apparently the toot! app uses those, but pinafore doesn't seem to.

**Comment by nolanlawson** [comment]
Yeah this would be a good thing to do alongside i18n which is currently on the list of possible future features. I'm not sure how cybre.space communicates that to the toot! app but I'm guessing it's a custom API or something.

**Comment by jemus42** [comment]
For what it's worth, the ＣＹＢＲＥtweaks are "just" a language thing:
![](https://dump.jemu.name/2018-08-xsv03zw0issz4nt.png)

I don't know anything about the API though.

**Comment by nolanlawson** [comment]
Looking into this again, I'm not sure how the Toot! app could even figure out that cybre.space calls them florps and relays, since it's not exposed in the API: `https://cybre.space/api/v1/instance/`. In contrast there is the unofficial `max_toot_chars` param which does expose the number of allowed characters in a toot (which is supported by Tusky and Pinafore, and is exposed by glitch-soc and some other servers).

I think this is maybe better-handled by custom Pinafore forks, such as pinafore.cybre.space. Closing for now.
