### ISSUE TITLE
"Unpin timeline" does nothing

### ISSUE THREAD

**Issue by stuartlangridge** [nolanlawson/pinafore#438]
In the "speech bubble" tab, I see listed "local timeline", "federated timeline", and "favourites". I have "favourites" pinned, but I'd like to unpin it. However, I don't seem to be able to; tapping the active-looking pin icon next to "favourites" doesn't seem to do anything.

**Comment by stuartlangridge** [comment]
Ah, so it's a radio button! See, this is why you don't reinvent existing controls :-) That being the case, then, showing the pin just on the pinned one would make it clearer, I think, and then tapping one of the other two would move the pin to the tapped one which would completely explain what was going on.

**Comment by nolanlawson** [comment]
I like this concept visually, but there needs to be a tappable area for the unpinned timelines, because if you tap on the whole thing then you just view the timeline. Maybe the solution is to just disable the "unpin" button or at least make it so it doesn't say "unpin" which is misleading.

Making them true radio buttons is another option; using a toggle button for this stuff is admittedly kinda wonky. 😜

**Comment by nolanlawson** [comment]
closing in favor of #1633 which describes this issue plus other issues with toggle buttons.
