### ISSUE TITLE
Can't log in to an instance using Chrome on iOS

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#462]
Reported by a user. Chrome specifically on iOS 10.

**Comment by narFnarF** [comment]
I was the one who reported this bug. If you have any questions or need some logs or whatever, don't hesitate!

Just to be clear, I have the exact same issue on Chrome AND Safari, on that phone. But yeah, my phone is still on iOS 10 (i don't want to upgrade because ios11 performance on my phone 5s are bad)

I'm attaching some screenshot of the non-working login flow:

![7ccc5488eb75f9b3](https://user-images.githubusercontent.com/3538115/44434428-0f3bc000-a579-11e8-8a4c-344c279d16dc.png)
↑As you can see, the "Log in" button remains disabled.

![a7f22cbf05dad2be](https://user-images.githubusercontent.com/3538115/44434431-11058380-a579-11e8-945a-a2ddae9baf4b.png)
↑If I press Enter on the virtual keyboard, i'm redirected to this empty page

I hope this helps!

**Comment by narFnarF** [comment]
I feel it's a different issue than https://github.com/nolanlawson/pinafore/issues/444 because on both browser, I didn't deactivated cookies.

**Comment by nolanlawson** [comment]
Thanks! BTW a good way to figure out what's going on may be to connect your iPhone to the desktop, then use Safari in developer mode and look at the console to see what the error is. Otherwise I will have to create a simulator of iOS 10 to reproduce. Which version of iOS 10 is this exactly?

**Comment by nolanlawson** [comment]
This is iOS 10.3.3

**Comment by nolanlawson** [comment]
Closing old issues, please let me know if this is still an issue. I'm guessing it's iOS 10 related. Thanks!

**Comment by KNTRO** [comment]
Hi there!

I'm a Pinafore new user. I got the very same bug, on old iOS 9.3.5. Asking for the full web version in iOS' Safari won't work either. 😥

> BTW a good way to figure out what's going on may be to connect your iPhone to the desktop, then use Safari in developer mode and look at the console to see what the error is.

I'm afraid I can't do this, since I'm using Windows in my desktop computer and the iOS Safari's _Web Inspector_ feature asks for the desktop's Safari web browser.
