### ISSUE TITLE
Show more/less is slow (Firefox mobile)

### ISSUE THREAD

**Issue by ariasuni** [nolanlawson/pinafore#63]
Given the speed of Pinafore, I would expect displaying/hiding a toot to be instant.

Instead, it’s (much) slower than Mastodon default web UI.

**Comment by nolanlawson** [comment]
Which version of Firefox/Android and what kind of phone are you running? On Firefox 59 on Android 7 on a GS5 it seems fast for me. Although I do make it skip a frame using `requestAnimationFrame()` for the benefit of input responsiveness, but you shouldn't be able to notice a 16ms delay. :)

**Comment by nolanlawson** [comment]
Looking at the code, the main difference I see between Pinafore and Mastodon is that Mastodon injects the status content into the DOM immediately, then toggles `display:none` when you tap the button. That's probably why it's so fast. Whereas Pinafore doesn't inject (or even parse the HTML or hydrate hashtags/mentions) until you tap the button.

So it takes a bit longer, but the tradeoff is that it's faster to actually load the toot with the spoiler hidden, which I think may be the right tradeoff since it gets the main content onto the page faster. But this is worth investigating further.

**Comment by ariasuni** [comment]
I use Firefox 60.0, LineageOS 14.1 (Android 7.1.2), Huawei Honor 5X.

It does seem to take 3/4 of a second, which definitely does not seem fast to me.

**Comment by vivlim** [comment]
I'd really like for this to be configurable, there are networks and machines which I'd rather not prefetch & cache CW'd content on.
