### ISSUE TITLE
Show full datetime as alt text of relative times

### ISSUE THREAD

**Issue by Lucidiot** [nolanlawson/pinafore#759]
When opening a single toot, the toot's timestamp is shown as a full datetime (`February 31st, 7:14PM`) whereas the related toots (every other toot in the thread) have their timestamps shown as relative times `4 hours ago`. When hovering over the link, a tooltip shows the exact same relative time, `4 hours ago`. To see the full datetime, I have to open the post. The tooltip could just show the full datetime.

As I understand it, the relative datetime is handled by the [StatusRelativeDate](https://github.com/nolanlawson/pinafore/blob/master/routes/_components/status/StatusRelativeDate.html) component; I can try opening a pull request, but I would like to know how I should be formatting the date instead. ISO 8601? Or is there a utility function somewhere to do the right formatting?

**Comment by nolanlawson** [comment]
We could get the absolute datetime the same we we do it for the focused view, which is in [StatusDetails here](https://github.com/nolanlawson/pinafore/blob/481a56780703f9d5e359353df90ad0c50d654dce/routes/_components/status/StatusDetails.html#L174-L175).

One thing I'm worried about, though, is accessibility. Screenreaders ignore the `title`, right? I wouldn't want screenreader users to have to hear the full timestamp instead of the short "4 hours ago."

**Comment by Fidgetcetera** [comment]
Most screen readers do ignore `title`, yes. https://silktide.com/i-thought-title-text-improved-accessibility-i-was-wrong/
