### ISSUE TITLE
Delete and redraft causes immediate delete

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#828]
This means that you can't change your mind if you click "delete and redraft." Ideally the original toot would only be deleted once you click "toot."

Unfortunately this means we need a better solution to the "delete and redraft" modal, as right now it's using the same backing realm as the main compose modal. Ideally it should have its own.

**Comment by nolanlawson** [comment]
On second thought, I don't believe this is a bug. When I choose "delete and redraft," it would cause me anxiety if I knew that the toot was still out there until I edited it. Deleting it immediately means I can redraft at my leisure.

**Comment by strypey** [comment]
Is there any way this could be handled differently on desktop than on mobile? On desktop I'm totally happy with the post being deleted right away. But with a touchscreen interface I've had a number of experiences with failing to successfully redraft due to accidentally touching the wrong part of the screen and dismissing the compose pop-up etc. On mobile, I'd prefer the original post to be deleted only as the new one is being successfully posted. Is it possible to make this a setting that can be toggled according to what works for each user on each device?

**Comment by nolanlawson** [comment]
@strypey You can always reopen the compose popup (i.e. by scrolling down on the home timeline and pressing the pen icon) and the data will still be there.

**Comment by strypey** [comment]
Good to know! Is there any way to make the modal refuse to be dismissed unless its contents are posted (again this is mainly an issue for me on mobile)? Maybe also with an explicit 'cancel' control for when users start to redraft and then realize we actually just want to leave it at delete?
